export const arrayofProducts = [
    {
      "colors": ["brown", "beige"],
      "name": "Modern Sofa Set",
      "description": "Luxurious modern sofa set made with premium fabric and a durable wooden frame.",
      "price": 1200,
      "originalPrice": 1500,
      "discount": 20,
      "tags": ["new", "luxury", "living-room"],
      "sizes": ["Large", "Medium"],
      "stock": 10,
      "color": "brown",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1578898887068-ec7c2984724e"
    },
    {
      "colors": ["white", "gray"],
      "name": "Dining Table Set",
      "description": "Elegant dining table set with six chairs, crafted from solid oak.",
      "price": 800,
      "originalPrice": 1000,
      "discount": 20,
      "tags": ["dining", "wooden", "new-arrival"],
      "sizes": ["Large"],
      "stock": 15,
      "color": "white",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4"
    },
    {
      "colors": ["black"],
      "name": "Office Chair",
      "description": "Ergonomic office chair with adjustable height and lumbar support.",
      "price": 150,
      "originalPrice": 250,
      "discount": 40,
      "tags": ["office", "ergonomic", "sale"],
      "sizes": ["Standard"],
      "stock": 25,
      "color": "black",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1616627451973-0a17d2701a0c"
    },
    {
      "colors": ["dark-brown"],
      "name": "Bookshelf",
      "description": "Spacious wooden bookshelf with a modern design for all your storage needs.",
      "price": 300,
      "originalPrice": 450,
      "discount": 33,
      "tags": ["storage", "bookshelf", "modern"],
      "sizes": ["Medium", "Tall"],
      "stock": 20,
      "color": "dark-brown",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1616627746518-38ef4f5fcd5f"
    },
    {
      "colors": ["blue", "gray"],
      "name": "Recliner Chair",
      "description": "Comfortable recliner chair with a sleek design and soft fabric upholstery.",
      "price": 400,
      "originalPrice": 600,
      "discount": 33,
      "tags": ["comfort", "living-room", "new"],
      "sizes": ["Standard"],
      "stock": 8,
      "color": "blue",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1598300055674-0f07dbf208c2"
    },
    {
      "colors": ["white"],
      "name": "TV Console Table",
      "description": "Stylish TV console table with storage drawers and a minimalist look.",
      "price": 350,
      "originalPrice": 500,
      "discount": 30,
      "tags": ["living-room", "minimalist"],
      "sizes": ["Medium"],
      "stock": 12,
      "color": "white",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1595329457002-b9c62d6528b2"
    },
    {
      "colors": ["beige"],
      "name": "Accent Chair",
      "description": "Elegant accent chair for adding a touch of class to your living space.",
      "price": 220,
      "originalPrice": 350,
      "discount": 37,
      "tags": ["accent", "living-room", "elegant"],
      "sizes": ["Standard"],
      "stock": 18,
      "color": "beige",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1578898886860-84ff3c0353d1"
    },
    {
      "colors": ["dark-gray"],
      "name": "King Size Bed",
      "description": "Spacious king-size bed with a sturdy frame and high-quality mattress.",
      "price": 1400,
      "originalPrice": 1800,
      "discount": 22,
      "tags": ["bedroom", "king-size", "comfortable"],
      "sizes": ["King"],
      "stock": 5,
      "color": "dark-gray",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1505692794405-e2534be9c9a1"
    },
    {
      "colors": ["light-wood"],
      "name": "Coffee Table",
      "description": "Minimalist coffee table with a light wood finish and a sturdy base.",
      "price": 250,
      "originalPrice": 400,
      "discount": 38,
      "tags": ["living-room", "coffee-table", "minimalist"],
      "sizes": ["Standard"],
      "stock": 14,
      "color": "light-wood",
      "authorId": "677ed475a7e3ab4efcd42200",
      "images": "https://images.unsplash.com/photo-1598300055674-0f07dbf208c2"
    },
        {
          "colors": ["brown", "beige"],
          "name": "Modern Sofa Set",
          "description": "Luxurious modern sofa set made with premium fabric and a durable wooden frame.",
          "price": 1200,
          "originalPrice": 1500,
          "discount": 20,
          "tags": ["new", "luxury", "living-room"],
          "sizes": ["Large", "Medium"],
          "stock": 10,
          "color": "brown",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1578898887068-ec7c2984724e"
        },
        {
          "colors": ["black", "white"],
          "name": "Elegant Dining Table",
          "description": "Stunning dining table with a glossy finish and sturdy metal frame.",
          "price": 800,
          "originalPrice": 1000,
          "discount": 20,
          "tags": ["elegant", "dining", "furniture"],
          "sizes": ["Standard"],
          "stock": 5,
          "color": "black",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1560448204-e8131a4d0b35"
        },
        {
          "colors": ["gray", "blue"],
          "name": "Premium Office Chair",
          "description": "Ergonomic office chair with adjustable height and lumbar support.",
          "price": 250,
          "originalPrice": 300,
          "discount": 17,
          "tags": ["office", "chair", "comfortable"],
          "sizes": ["Adjustable"],
          "stock": 15,
          "color": "gray",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1579338555868-dfd5070b99a7"
        },
        {
          "colors": ["white", "gold"],
          "name": "Luxury Bed Frame",
          "description": "Elegant bed frame with a gold-finish and cushioned headboard.",
          "price": 1500,
          "originalPrice": 1800,
          "discount": 16,
          "tags": ["bedroom", "luxury", "furniture"],
          "sizes": ["King", "Queen"],
          "stock": 8,
          "color": "white",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1585559605684-1a7b94a6bc06"
        },
        {
          "colors": ["brown", "green"],
          "name": "Classic Wooden Table",
          "description": "Handcrafted wooden table perfect for dining and work.",
          "price": 600,
          "originalPrice": 750,
          "discount": 20,
          "tags": ["classic", "wooden", "multi-purpose"],
          "sizes": ["Standard"],
          "stock": 12,
          "color": "brown",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1598300054858-7fba2f78ffbb"
        },
        {
          "colors": ["gray", "black"],
          "name": "Minimalist TV Stand",
          "description": "Modern TV stand with ample storage and cable management.",
          "price": 400,
          "originalPrice": 500,
          "discount": 20,
          "tags": ["minimalist", "tv-stand", "living-room"],
          "sizes": ["Large"],
          "stock": 7,
          "color": "gray",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1583946061785-a75b4e98e517"
        },
        {
          "colors": ["blue", "white"],
          "name": "Cozy Bean Bag",
          "description": "Soft and durable bean bag for a comfortable seating experience.",
          "price": 120,
          "originalPrice": 150,
          "discount": 20,
          "tags": ["cozy", "bean-bag", "seating"],
          "sizes": ["Large"],
          "stock": 20,
          "color": "blue",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1602825016951-04af49c504fa"
        },
        {
          "colors": ["white", "brown"],
          "name": "Modern Coffee Table",
          "description": "Stylish coffee table with a sleek finish and ample space.",
          "price": 350,
          "originalPrice": 450,
          "discount": 22,
          "tags": ["modern", "coffee-table", "furniture"],
          "sizes": ["Medium"],
          "stock": 6,
          "color": "white",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1598300053823-5a6a91dcf6d8"
        },
        {
          "colors": ["black", "gold"],
          "name": "Industrial Bookshelf",
          "description": "Rustic bookshelf with a durable metal frame and wooden shelves.",
          "price": 450,
          "originalPrice": 550,
          "discount": 18,
          "tags": ["industrial", "bookshelf", "storage"],
          "sizes": ["Large"],
          "stock": 10,
          "color": "black",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1587306229365-b10c7a2486bd"
        },
        {
          "colors": ["red", "gray"],
          "name": "Comfy Recliner",
          "description": "Recliner chair with a plush design for maximum relaxation.",
          "price": 900,
          "originalPrice": 1100,
          "discount": 18,
          "tags": ["recliner", "comfortable", "luxury"],
          "sizes": ["Adjustable"],
          "stock": 4,
          "color": "red",
          "authorId": "677ed475a7e3ab4efcd42200",
          "images": "https://images.unsplash.com/photo-1590532596311-7a30bb3906f8"
        }
      
      
  ]
  